//! Core agent loop: multi-round tool use until the model stops calling tools.
//!
//! Strongly inspired by Raven Hotel's agent_runtime (MAX_TOOL_ROUNDS, strict
//! "never hallucinate success", prefer patch, Think/Act/Report discipline).

use anyhow::Result;

use crate::agent_system_prompt::system_message;
use crate::chat_backend::ChatBackend;
use crate::config::Config;
use crate::judge::Judge;
use crate::llm::{ChatRequest, Message, StreamChunk, ToolCall};
use crate::tools;
use serde_json::json;
use std::path::Path;
use std::sync::Arc;
use tokio::sync::mpsc;
use tokio::sync::Mutex;

fn make_rel_path(p: &str, workspace: &Path) -> String {
    let abs = std::path::Path::new(p);
    if let Ok(stripped) = abs.strip_prefix(workspace) {
        stripped.to_string_lossy().to_string()
    } else if abs.is_absolute() {
        // fallback: last components
        abs.file_name()
            .map(|n| n.to_string_lossy().to_string())
            .unwrap_or_else(|| p.to_string())
    } else {
        p.to_string()
    }
}

fn normalize_agent_mode(s: &str) -> String {
    match s.trim().to_lowercase().as_str() {
        "talk" | "think" | "research" | "work" | "dream" | "plan" => s.trim().to_lowercase(),
        _ => "talk".to_string(),
    }
}

// Summary and truncation limits (from glm review cleanup)
const SUMMARY_CHAR_LIMIT: usize = 1600;
const GOAL_TRUNCATE: usize = 160;
const RECENT_SUMMARY_TRUNCATE: usize = 1800;

#[derive(Debug, Clone)]
pub struct ActionRecord {
    pub tool: String,
    #[allow(dead_code)]
    pub args: String,
    pub summary: String,
    /// Sanitized + truncated payload fed back to the model.
    pub output_to_model: String,
    #[allow(dead_code)]
    pub raw_bytes: usize,
    pub truncated: bool,
    /// Rough token estimate for the content sent to the model (for cache/efficiency metrics).
    pub estimated_tokens: u32,
}

#[derive(Debug, Clone, Default)]
pub struct TurnMetrics {
    pub llm_rounds: u32,
    pub tool_calls: u32,
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
    pub total_tokens: u64,
    /// Rough sum of estimated tokens in tool outputs delivered to the model.
    /// Useful for measuring cache effectiveness (e.g. summaries vs full reads).
    pub estimated_tool_tokens: u64,
    /// Number of times a cached file summary was served (read_summary hit).
    pub cache_summary_hits: u32,
    /// Estimated tokens delivered via fresh summaries (the "cached" cheap path).
    pub estimated_summary_tokens: u64,
    pub round_limit_hit: bool,
}

#[derive(Debug)]
pub struct TurnResult {
    pub final_text: String,
    pub actions: Vec<ActionRecord>,
    #[allow(dead_code)]
    pub rounds_used: u32,
    pub metrics: TurnMetrics,
    pub judge: Option<TurnJudge>,
}

/// Outcome from the inference-based judge used by the driver loop.
/// The judge looks at the declared goal + achievement_tests + recent actions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TurnJudge {
    /// The goal + success criteria appear to be satisfied.
    Fulfilled { note: String },
    /// Normal situation — continue working (nudging may still be appropriate).
    /// When completion_criteria (define_done) is active we attach a
    /// one-line suggestion generated by the judge itself so the nudge can say
    /// "run the script and show/paste the exact output" when that's what the
    /// definition requires.
    Continue { suggestion: Option<String> },
    /// Detected unproductive looping / thrashing.
    /// The agent should stop and ask the user for guidance.
    Stuck {
        reason: String,
        suggested_guidance: String,
    },
}

impl TurnJudge {
    /// Parse a TurnJudge from the log content format: "⭐ JUDGE (criteria active): {:?}"
    pub fn from_log_content(content: &str) -> Option<Self> {
        // Expected format: "⭐ JUDGE (criteria active): Fulfilled { note: \"...\" }"
        const PREFIX: &str = "⭐ JUDGE (criteria active): ";
        let content = content.strip_prefix(PREFIX)?;

        // Try to parse as Fulfilled { note: "..." }
        if let Some(note) = extract_quoted(content, "Fulfilled { note: \"", "\" }") {
            return Some(TurnJudge::Fulfilled {
                note: note.to_string(),
            });
        }

        // Try to parse as Stuck { reason: "...", suggested_guidance: "..." }
        if let (Some(reason), Some(suggested_guidance)) = (
            extract_quoted(content, "Stuck { reason: \"", "\""),
            extract_quoted(content, "suggested_guidance: \"", "\" }"),
        ) {
            return Some(TurnJudge::Stuck {
                reason: reason.to_string(),
                suggested_guidance: suggested_guidance.to_string(),
            });
        }

        // Try to parse as Continue { suggestion: Some("...") } or Continue { suggestion: None }
        if content.starts_with("Continue { suggestion: ") {
            let suggestion = if content.contains("Some(\"") {
                extract_quoted(content, "Some(\"", "\") }")
            } else {
                None
            };
            return Some(TurnJudge::Continue {
                suggestion: suggestion.map(|s| s.to_string()),
            });
        }

        None
    }
}

fn extract_quoted<'a>(s: &'a str, prefix: &str, suffix: &str) -> Option<&'a str> {
    let start = s.find(prefix)?;
    let start = start + prefix.len();
    let end = s[start..].find(suffix)?;
    Some(&s[start..start + end])
}

pub struct Agent {
    client: Arc<Mutex<ChatBackend>>,
    config: Config,
    /// Clean conversation turns only (user / assistant / tool). Latest user inputs
    /// are pushed here (via record/on_new) so the model sees proper user turns.
    /// The rich session context (repo tree, goal, pitfalls, recent summary, latest
    /// user header) is injected fresh on every prompt construction.
    pub(crate) conversation: Vec<Message>,
    /// Persistent session (goal tracking off by default via RAVEN_GOAL_TRACKING=1, repo cache, full log, meta.json under ~/.raven-hotel/)
    pub(crate) session: Option<crate::session::Session>,
    /// How many conversation messages have been written to full_log.jsonl.
    logged_message_count: usize,
    /// Judge for inference-based task completion decisions
    judge: Option<crate::judge::Judge>,
    /// Brave Search API key (decrypted, set by TUI from keystore).
    pub brave_key: Option<String>,
    /// Mirror of TUI plan execution state (synced before each turn).
    pub plan_exec: crate::plan_execution::PlanExecutionState,
}

impl Agent {
    pub fn new(mut config: Config, client: ChatBackend) -> Self {
        // Use prebuilt session from main (if provided) so that trust prompt + repo
        // cache bootstrap performed before launching the TUI / --prompt is connected.
        // When prebuilt_session is None (e.g. --no-session), the agent runs without
        // any session — no conversation history, no goal tracking, no injection block.
        let prebuilt = std::mem::take(&mut config.prebuilt_session);
        let session = prebuilt;
        let mut conversation = vec![];

        // Restore recent conversation from the persistent log (now includes user
        // turns) so the model remembers after a restart (Ctrl+C / crash).
        if let Some(s) = &session {
            let recent = s.load_recent_conversation(20);
            for (role, content) in recent {
                let clean = if role == "assistant" {
                    crate::llm::strip_xml_tool_call_blocks(&content)
                } else {
                    content
                };
                if !clean.trim().is_empty() {
                    conversation.push(Message {
                        role,
                        content: Some(clean),
                        tool_calls: None,
                        tool_call_id: None,
                    });
                }
            }
        }

        let logged_message_count = conversation.len();
        let client_arc = Arc::new(Mutex::new(client));

        Self {
            client: client_arc.clone(),
            config,
            conversation,
            session,
            logged_message_count,
            judge: Some(Judge::new(client_arc)),
            brave_key: None,
            plan_exec: crate::plan_execution::PlanExecutionState::default(),
        }
    }

    pub fn set_plan_execution(&mut self, state: crate::plan_execution::PlanExecutionState) {
        self.plan_exec = state;
    }

    pub fn plan_execution(&self) -> &crate::plan_execution::PlanExecutionState {
        &self.plan_exec
    }

    pub fn workspace(&self) -> &std::path::Path {
        &self.config.workspace
    }

    pub fn plan_tool_context(&self) -> tools::PlanToolContext {
        tools::PlanToolContext {
            plan_executing: self.plan_exec.active && !self.plan_exec.steps.is_empty(),
        }
    }

    /// Record a user reply for a pending observe-tier plan step.
    pub fn apply_user_observation(&mut self, reply: &str) -> Option<String> {
        let mut session_take = self.session.take();
        let out = crate::plan_execution::submit_user_observation(
            &mut self.plan_exec,
            reply,
            session_take.as_mut(),
        );
        self.session = session_take;
        out
    }

    fn tools_for_current_mode(&self) -> Vec<crate::llm::ToolDef> {
        tools::tools_for_agent(
            &self.current_agent_mode(),
            &self.config.flags,
            self.plan_tool_context(),
        )
    }

    /// Reset conversation (new "room" / task). The persistent session (goal, repo cache, log) is kept.
    pub fn reset(&mut self) {
        self.conversation.clear();
        self.logged_message_count = 0;
    }

    /// Get a reference to the session.
    pub fn session(&self) -> &Option<crate::session::Session> {
        &self.session
    }

    /// Get a mutable reference to the session.
    pub fn session_mut(&mut self) -> &mut Option<crate::session::Session> {
        &mut self.session
    }

    /// LLM client for harness-side classifiers (plan intent, etc.).
    pub fn llm_backend(&self) -> Arc<Mutex<ChatBackend>> {
        self.client.clone()
    }

    /// Truncate tool output to fit the context budget.
    fn truncate_for_context(&self, s: &str) -> String {
        truncate_for_context(s, self.config.context_budget.tool_result_bytes)
    }

    fn record_tool_action(&self, tool: &str, args: &str, raw_output: &str) -> ActionRecord {
        let sanitized = crate::sanitize::tool_output(raw_output);
        let budget = self.config.context_budget.tool_result_bytes;
        let truncated = sanitized.len() > budget;
        let to_model = self.truncate_for_context(&sanitized);
        let estimated = estimate_tokens(&to_model);
        ActionRecord {
            tool: tool.to_string(),
            args: args.to_string(),
            summary: to_model.lines().next().unwrap_or("").to_string(),
            output_to_model: to_model,
            raw_bytes: raw_output.len(),
            truncated,
            estimated_tokens: estimated,
        }
    }

    /// High level entry: give the agent a user goal and let it run until it stops using tools.
    ///
    /// This delegates to `agent_driver::drive_turn()` with a `SilentObserver`,
    /// so it uses the exact same driving loop as the interactive TUI (nudges,
    /// auto-continue, streaming, etc.).
    #[allow(dead_code)]
    pub async fn run_turn(&mut self, user_input: &str) -> Result<TurnResult> {
        let mut observer = crate::agent_driver::SilentObserver;
        crate::agent_driver::drive_turn(self, user_input, &mut observer).await
    }

    /// Get a streaming turn. The caller is responsible for consuming chunks and
    /// calling `feed_tool_result` when tool calls are completed.
    #[allow(dead_code)]
    pub async fn run_turn_streaming(
        &mut self,
        user_input: &str,
    ) -> Result<tokio::sync::mpsc::Receiver<StreamChunk>> {
        self.on_new_user_input(user_input);
        self.prune_history().await;

        let messages = self.build_messages_for_model();
        let tools = self.tools_for_current_mode();
        let req = ChatRequest {
            messages,
            tools: Some(tools),
            temperature: self.config.temperature,
            max_tokens: self.config.max_tokens,
            stream: true,
            reasoning_enabled: None,
            json_object_mode: None,
        };

        self.client.lock().await.chat_stream(req).await
    }

    /// After a streaming turn produced tool calls, execute them and append the
    /// tool results to conversation so the next `run_turn_streaming` can continue.
    pub async fn execute_and_record_tool_calls(
        &mut self,
        tool_calls: &[ToolCall],
    ) -> Vec<ActionRecord> {
        let mut records = vec![];
        for tc in tool_calls {
            let tool_name = tc.function.name.clone();
            let raw_args = tc.function.arguments.clone();

            // Invalidate summaries for mutations *before* execution
            let args_val: serde_json::Value = serde_json::from_str(&raw_args).unwrap_or(json!({}));
            self.maybe_invalidate_summary(&tool_name, &args_val);

            // Intercept session tools (goal, discovery, summaries)
            if let Some(ack) = self.handle_session_tool(&tool_name, &raw_args).await {
                let rec = self.record_tool_action(&tool_name, &raw_args, &ack);
                let to_model = rec.output_to_model.clone();
                records.push(rec);
                self.conversation.push(Message {
                    role: "tool".into(),
                    content: Some(to_model),
                    tool_calls: None,
                    tool_call_id: Some(tc.id.clone()),
                });
                continue;
            }

            // Plan mode guard (belt & suspenders for direct calls).
            if let Some(denial) = self.plan_mode_denial(&tool_name, &raw_args) {
                self.record_tool_denial(tc, &denial);
                // Create a record so the driver surfaces it in the trace pane too.
                let rec = ActionRecord {
                    tool: tool_name.clone(),
                    args: raw_args.clone(),
                    summary: denial.clone(),
                    output_to_model: denial,
                    raw_bytes: 0,
                    truncated: false,
                    estimated_tokens: 10,
                };
                records.push(rec);
                continue;
            }

            let output = tools::execute(
                &self.config.tool_backend,
                &tool_name,
                &raw_args,
                &self.config.workspace,
                self.config.context_budget.read_line_limit,
                self.brave_key.clone(),
            )
            .await
            .unwrap_or_else(|e| format!("❌ Tool error: {}", e));

            // Brave key rejected: drop session key so we stop re-sending a dead token.
            if tool_name == "web_search"
                && (tools::brave_auth_disabled()
                    || tools::web_search_reports_brave_auth_rejected(&output))
            {
                self.brave_key = None;
            }

            let rec = self.record_tool_action(&tool_name, &raw_args, &output);
            let to_model = rec.output_to_model.clone();
            records.push(rec);

            self.conversation.push(Message {
                role: "assistant".into(),
                content: None,
                tool_calls: Some(vec![tc.clone()]),
                tool_call_id: None,
            });

            self.conversation.push(Message {
                role: "tool".into(),
                content: Some(to_model),
                tool_calls: None,
                tool_call_id: Some(tc.id.clone()),
            });
        }
        self.persist_turn().await;
        records
    }

    /// Record a denied tool call into conversation (so the model sees a tool result)
    /// without actually executing the side effect.
    /// Returns a denial reason string if the tool is blocked due to being in Plan mode
    /// (and it's not a wiki write/patch). Returns None if the tool is allowed.
    pub fn plan_mode_denial(&self, tool_name: &str, arguments: &str) -> Option<String> {
        if self.current_agent_mode() != "plan" {
            return None;
        }
        if !matches!(tool_name, "write" | "patch" | "download") {
            return None;
        }
        if tool_name == "download" {
            return Some(
                "❌ download denied while in Plan mode (clarification phase). \
                 Wait for proceed, then download assets into the project workdir."
                    .to_string(),
            );
        }
        let args_val: serde_json::Value = serde_json::from_str(arguments).unwrap_or_default();
        let mut is_wiki = false;
        if tool_name == "write" || tool_name == "patch" {
            if let Some(w) = args_val.get("wiki").and_then(|v| v.as_bool()) {
                is_wiki = w;
            }
            if !is_wiki {
                if let Some(p) = args_val.get("path").and_then(|v| v.as_str()) {
                    let t = p.trim().trim_start_matches("./");
                    if t.starts_with("wiki/") || t.starts_with("wiki\\") || t == "wiki" {
                        is_wiki = true;
                    }
                }
            }
        }
        if is_wiki {
            None
        } else {
            Some("❌ write/patch denied while in Plan mode (clarification phase). You must confirm verification steps + rollback and receive an explicit 'proceed' (or equivalent) before writing implementation files. Use wiki writes only for plan.md during planning.".to_string())
        }
    }

    pub fn record_tool_denial(&mut self, tc: &ToolCall, reason: &str) {
        self.conversation.push(Message {
            role: "assistant".into(),
            content: None,
            tool_calls: Some(vec![tc.clone()]),
            tool_call_id: None,
        });
        self.conversation.push(Message {
            role: "tool".into(),
            content: Some(reason.to_string()),
            tool_calls: None,
            tool_call_id: Some(tc.id.clone()),
        });
    }

    pub fn push_assistant_text(&mut self, text: &str) {
        self.conversation.push(Message {
            role: "assistant".into(),
            content: Some(text.to_string()),
            tool_calls: None,
            tool_call_id: None,
        });
        // Log to persistent full_log so it survives restarts
        if let Some(s) = &self.session {
            let entry = serde_json::json!({
                "ts": chrono::Utc::now().to_rfc3339(),
                "role": "assistant",
                "content": text,
                "has_tool_calls": false,
            });
            let _ = s.append_log(&entry.to_string());
        }
    }

    /// Push a brief nudge into the conversation when the model pauses
    /// to narrate instead of continuing to call tools.
    pub fn push_continuation_nudge(&mut self) {
        let msg = if self.config.flags.is_eval {
            let mut m = crate::agent_driver::CONTINUATION_NUDGE.to_string();
            // Gentle re-anchor to original goal (environment helping the model stay on task) -- eval only
            if let Some(s) = &self.session {
                if let Some(req) = &s.meta.last_user_request {
                    let short = if req.len() > 300 { &req[..300] } else { req };
                    m.push_str(&format!("\n\n(Original request reminder: {})", short));
                }
            }
            m
        } else {
            crate::agent_driver::CONTINUATION_NUDGE.to_string()
        };
        self.conversation.push(Message {
            role: "user".into(),
            content: Some(msg),
            tool_calls: None,
            tool_call_id: None,
        });
    }

    /// Continue with another streaming inference using the *current* conversation
    /// (no extra user message is pushed). This is used after tool results have
    /// already been appended.
    #[allow(dead_code)]
    pub async fn continue_turn_streaming(&mut self) -> Result<mpsc::Receiver<StreamChunk>> {
        self.prune_history().await;
        let messages = self.build_messages_for_model();
        let tools = self.tools_for_current_mode();
        let req = ChatRequest {
            messages,
            tools: Some(tools),
            temperature: self.config.temperature,
            max_tokens: self.config.max_tokens,
            stream: true,
            reasoning_enabled: None,
            json_object_mode: None,
        };
        self.client.lock().await.chat_stream(req).await
    }

    /// Send a streaming request with optional tool schemas.
    /// Used by `agent_driver::drive_turn()` as the canonical inference call.
    pub async fn send_streaming_request(
        &mut self,
        tools: Option<Vec<crate::llm::ToolDef>>,
    ) -> Result<mpsc::Receiver<StreamChunk>> {
        self.prune_history().await;
        let messages = self.build_messages_for_model();
        let req = ChatRequest {
            messages,
            tools,
            temperature: self.config.temperature,
            max_tokens: self.config.max_tokens,
            stream: true,
            reasoning_enabled: None,
            json_object_mode: None,
        };
        self.client.lock().await.chat_stream(req).await
    }

    /// Push an arbitrary message into the conversation (for nudges, system notes, etc.).
    pub fn push_message(&mut self, role: &str, content: &str) {
        self.conversation.push(Message {
            role: role.into(),
            content: Some(content.into()),
            tool_calls: None,
            tool_call_id: None,
        });
        // Log immediately (with current ts) so full_log order matches conversation order.
        // Advance count so persist_turn won't duplicate.
        if let Some(s) = &self.session {
            let entry = serde_json::json!({
                "ts": chrono::Utc::now().to_rfc3339(),
                "role": role,
                "content": content,
                "has_tool_calls": false,
            });
            let _ = s.append_log(&entry.to_string());
            self.logged_message_count = self.conversation.len();
        }
    }

    /// Append a harness-internal diagnostic event directly to full_log.jsonl
    /// *without* adding it to the model's conversation history.
    ///
    /// This keeps nudge/judge/trace info available for:
    /// - Human debugging of harness behavior (in raven_log.jsonl etc.)
    /// - The agent itself grepping its own full run log (when working from
    ///   summarized recent_turns_summary + wanting to recover exact nudge/judge
    ///   details).
    ///
    /// Use distinct "role": "system" (or event type) so that normal conversation
    /// reconstruction and build_messages_for_model ignore these. The model is
    /// instructed to ignore [DEBUG ...] / harness notes anyway.
    pub fn log_harness_event(&self, event: &str, content: &str) {
        if let Some(s) = &self.session {
            let entry = serde_json::json!({
                "ts": chrono::Utc::now().to_rfc3339(),
                "role": "system",
                "event": event,
                "content": content,
            });
            let _ = s.append_log(&entry.to_string());
        }
    }

    /// Convenience for harness events that also want the current LLM round.
    pub fn log_harness_event_with_round(&self, event: &str, content: &str, round: u32) {
        if let Some(s) = &self.session {
            let entry = serde_json::json!({
                "ts": chrono::Utc::now().to_rfc3339(),
                "role": "system",
                "event": event,
                "round": round,
                "content": content,
            });
            let _ = s.append_log(&entry.to_string());
        }
    }

    /// Context management (evolved for sessions).
    /// We keep the *conversation* (user/assistant/tool turns) bounded.
    /// The rich repo + goal + recent summary lives in the Session and is injected
    /// fresh every time we build the prompt (see build_messages_for_model).
    async fn prune_history(&mut self) {
        const MAX_CONVERSATION: usize = 48;
        const MIN_TO_SUMMARIZE: usize = 6;

        if self.conversation.len() <= MAX_CONVERSATION {
            return;
        }

        let start = self.conversation.len() - MAX_CONVERSATION;
        let dropped = self.conversation[..start].to_vec();
        let recent = self.conversation[start..].to_vec();

        if dropped.len() >= MIN_TO_SUMMARIZE {
            let summary = self.summarize_messages(&dropped).await;
            // Push the compression into the session's rolling "recent turns" summary
            // (the injection block will surface a version of it).
            let label = self.generate_session_label().await;
            if let Some(s) = &mut self.session {
                let combined = if s.meta.recent_turns_summary.is_empty() {
                    summary.clone()
                } else {
                    format!("{}\n\n(earlier)\n{}", s.meta.recent_turns_summary, summary)
                };
                // Keep it small
                let trimmed = if combined.len() > RECENT_SUMMARY_TRUNCATE {
                    tools::safe_truncate(&combined, RECENT_SUMMARY_TRUNCATE).to_string() + "..."
                } else {
                    combined
                };
                let _ = s.set_recent_turns_summary(&trimmed);

                // Also refresh the short label when we rewrite summary on prune
                let _ = s.set_session_label(&label);
            }
        }

        self.conversation = recent;
    }

    /// Ask the model (without tools) to produce a compact summary of a batch of
    /// older messages. This is our main "compression" mechanism.
    async fn summarize_messages(&self, msgs: &[Message]) -> String {
        if msgs.is_empty() {
            return String::new();
        }

        let history_dump = msgs
            .iter()
            .map(|m| {
                let role = &m.role;
                let content = m.content.as_deref().unwrap_or("");
                let tc = if let Some(tcs) = &m.tool_calls {
                    format!(
                        " [tool_calls: {}]",
                        tcs.iter()
                            .map(|t| t.function.name.as_str())
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                } else {
                    "".to_string()
                };
                format!("{role}: {content}{tc}")
            })
            .collect::<Vec<_>>()
            .join("\n\n");

        let summary_prompt = if self.config.flags.is_eval {
            // Strong anti-rabbithole + task anchoring only for evals
            let (goal, criteria) = if let Some(s) = &self.session {
                (
                    s.meta.current_goal.as_str(),
                    s.meta.completion_criteria.as_deref().unwrap_or(""),
                )
            } else {
                ("", "")
            };

            let anchor = if !goal.is_empty() || !criteria.is_empty() {
                format!("\n\nORIGINAL TASK ANCHOR (summarize ONLY in service of this):\nGoal: {}\nCompletion Criteria: {}\n", goal, criteria)
            } else {
                String::new()
            };

            format!(
                r#"The following is older conversation history from an agent working on a coding bug fix task.{}

CRITICAL RULES FOR THIS SUMMARY:
- Produce ONLY a concise, factual record of concrete actions, files examined, code insights discovered, tool results, and measurable progress.
- ALWAYS anchor to the ORIGINAL top-level task/bug report and any Agent-Defined Completion Criteria above.
- DO NOT include, echo, or create: <command_context>, <task_description>, <user_query>, internal exploration plans, meta sub-tasks ("explore X to understand Y"), or new "user queries".
- If the history drifted into narrow implementation details or planning, summarize only the factual outcomes that matter for the original goal. Omit the drift.
- Output in short bullets or 1-2 tight paragraphs. Focus on what helps continue/finish the real bug fix.

History:
{}"#,
                anchor, history_dump
            )
        } else {
            // Original simple summary behavior for normal interactive use
            format!(
                "The following is older conversation history from an agent exploring/ working on a task in a codebase. Produce a concise, factual summary (bullet points or short paragraphs) of the key actions taken, files or information discovered, and current state of understanding. Omit low-value details. Focus on what would help the agent continue the original task effectively.\n\n{}",
                history_dump
            )
        };

        let req = ChatRequest {
            messages: vec![Message {
                role: "user".into(),
                content: Some(summary_prompt),
                tool_calls: None,
                tool_call_id: None,
            }],
            tools: None,
            temperature: 0.3,
            max_tokens: 800,
            stream: false,
            reasoning_enabled: None,
            json_object_mode: None,
        };

        let raw = match self.client.lock().await.chat(req).await {
            Ok(resp) => resp.content.trim().to_string(),
            Err(_e) => {
                // Better fallback: simple truncation instead of storing error string forever (glm.md review)
                let combined: String = msgs
                    .iter()
                    .map(|m| m.content.clone().unwrap_or_default())
                    .collect::<Vec<_>>()
                    .join(" ");
                let fallback = tools::safe_truncate(&combined, 400).to_string();
                format!(
                    "(summarization failed, using truncated fallback) {}",
                    fallback
                )
            }
        };

        if self.config.flags.is_eval {
            // Post-process only in eval to strip meta-task structures
            strip_command_context_blocks(&raw)
        } else {
            raw
        }
    }

    /// Produce a short (≤60 char) label describing the current session.
    /// This is cheap (heuristic) so it can be updated without the full summary cost.
    /// Called when writing the detailed recent_turns_summary, and can be called
    /// more frequently for the picker UI label.
    async fn generate_session_label(&self) -> String {
        let Some(sess) = &self.session else {
            return "Undetermined".to_string();
        };
        let m = &sess.meta;

        // Prefer last user request, cleaned
        if let Some(req) = &m.last_user_request {
            let mut s = req.trim().to_string();
            if let Some(nl) = s.find('\n') {
                s.truncate(nl);
            }
            s = s.trim().to_string();
            if !s.is_empty() {
                return tools::safe_truncate(&s, 60).to_string();
            }
        }

        // Next, current goal
        let goal = m.current_goal.trim();
        if !goal.is_empty() {
            return tools::safe_truncate(goal, 60).to_string();
        }

        // Fallback to first useful line of existing summary
        for line in m.recent_turns_summary.lines() {
            let l = line.trim();
            if l.len() > 8 && !l.starts_with('(') && !l.starts_with('-') {
                return tools::safe_truncate(l, 60).to_string();
            }
        }

        // Last resort from recent conversation
        let last: Vec<_> = self.conversation.iter().rev().take(3).collect();
        for msg in &last {
            if let Some(c) = &msg.content {
                let t = c.trim();
                if t.len() > 10 {
                    let first = t.lines().next().unwrap_or(t);
                    return tools::safe_truncate(first, 60).to_string();
                }
            }
        }

        "Undetermined".to_string()
    }

    // ─────────────────────────────────────────────────────────────────
    // Session-aware helpers (new context management)
    // ─────────────────────────────────────────────────────────────────

    /// Record a user request for metadata (last_user_request, goal seeding) and
    /// trace logging. Also pushes the (latest) user message into `conversation`
    /// as a normal user turn. This ensures the model receives fresh user inputs
    /// in proper alternating history (not only via the "Latest User Message"
    /// header in the injection block).
    pub fn record_user_request(&mut self, user_input: &str) {
        if let Some(s) = &mut self.session {
            let _ = s.set_last_user_request(user_input);
            if self.config.flags.goal_tracking {
                if self.config.flags.is_eval {
                    // Eval-specific goal seeding with heuristic to avoid chat fixation
                    let no_initial_goal = self.config.flags.no_initial_goal;
                    if !no_initial_goal
                        && (s.meta.current_goal.trim().is_empty()
                            || s.meta.current_goal.contains("not yet established"))
                    {
                        let lower = user_input.trim().to_lowercase();
                        if user_input.len() > 25
                            && !lower.starts_with("hello")
                            && !lower.starts_with("hi")
                            && !lower.starts_with("hey")
                            && !lower.contains("joke")
                            && !lower.contains("tool")
                        {
                            let g = tools::safe_truncate(user_input, GOAL_TRUNCATE);
                            let _ = s.update_goal(
                                &format!("Initial goal from user: {}", g),
                                None,
                                None,
                            );
                        }
                    }
                } else {
                    // For normal use with goal tracking enabled: seed from first
                    if s.meta.current_goal.contains("not yet established")
                        || s.meta.current_goal.trim().is_empty()
                    {
                        let g = tools::safe_truncate(user_input, GOAL_TRUNCATE);
                        let _ =
                            s.update_goal(&format!("Initial goal from user: {}", g), None, None);
                    }
                }
            }
        }

        // Log the request event to persistent full_log (for traces, evals, raven_log.jsonl).
        if let Some(s) = &self.session {
            let entry = serde_json::json!({
                "ts": chrono::Utc::now().to_rfc3339(),
                "role": "user",
                "content": user_input,
                "has_tool_calls": false,
            });
            let _ = s.append_log(&entry.to_string());
        }

        // Push into conversation so the model sees the latest user input as a
        // proper role:user turn in the messages array (fixes echo / missed follow-ups
        // in session mode).
        self.conversation.push(Message {
            role: "user".into(),
            content: Some(user_input.to_string()),
            tool_calls: None,
            tool_call_id: None,
        });

        // We directly logged the user entry. Advance so persist_turn (on tool-using
        // paths) won't duplicate-log this user entry from the conversation vec.
        if self.session.is_some() {
            self.logged_message_count = self.conversation.len();
        }

        // Make the define_done instruction explicitly visible in the full log
        // for debugging (e.g. "why didn't the agent call it?").
        if user_input.contains("define_done")
            || user_input.contains("Early in the task, call the `define_done`")
        {
            self.log_harness_event(
                "define_done_instruction",
                "Initial request contained explicit instruction to call define_done early (once, before heavy tool use / in first or second turn). This is critical for criteria-based judge nudging."
            );
        }
    }

    pub fn on_new_user_input(&mut self, user_input: &str) {
        // Delegates to record_user_request which now handles meta, logging,
        // and pushing the user message into conversation for all paths.
        self.record_user_request(user_input);
    }

    /// Build the exact messages array we will send to the model this turn.
    /// Always starts with a fresh system message containing the current
    /// repo cache + goal + pitfalls + recent summary from the Session.
    fn build_messages_for_model(&self) -> Vec<Message> {
        let mode = self.current_agent_mode();
        let base = system_message(
            &self.config.workspace,
            &self.config.flags,
            &mode,
            self.plan_tool_context(),
        );

        // Log the system prompt (including whether Core Loop was suppressed for evals)
        // into full_log on the very first build so we can see exactly what the model
        // was given for debugging (e.g. why define_done was or wasn't called).
        if self.conversation.is_empty() {
            if let Some(s) = &self.session {
                if let Some(content) = &base.content {
                    let entry = serde_json::json!({
                        "ts": chrono::Utc::now().to_rfc3339(),
                        "role": "system",
                        "content": content,
                        "note": "full system prompt used for this session (Core Loop omitted in RAVEN_EVAL mode)"
                    });
                    let _ = s.append_log(&entry.to_string());
                }
            }
        }

        let mut msgs = vec![];
        if let Some(s) = &self.session {
            let injection = s.get_injection_block(&self.config.flags, &self.current_agent_mode());
            let mut combined = if base.content.as_deref().unwrap_or("").is_empty() {
                injection
            } else {
                format!("{}\n\n{}", base.content.as_deref().unwrap_or(""), injection)
            };
            let plan_block = crate::plan_execution::format_plan_execution_injection(
                &self.plan_exec,
                &self.config.workspace,
            );
            if !plan_block.is_empty() {
                combined.push_str("\n\n");
                combined.push_str(&plan_block);
            }
            msgs.push(Message {
                role: "system".into(),
                content: Some(combined),
                tool_calls: None,
                tool_call_id: None,
            });
        } else {
            msgs.push(base);
        }

        // Append the actual conversation turns (already pruned)
        msgs.extend(self.conversation.iter().cloned());

        // Legacy synthetic user marker (eval-only) as a fallback if conversation is
        // somehow empty on first build for a session (e.g. after reset + record edge).
        // With user inputs now pushed to conversation, this is rarely reached.
        // Kept to protect against local servers that dislike pure-system prompts.
        if self.config.flags.is_eval && self.session.is_some() && self.conversation.is_empty() {
            msgs.push(Message {
                role: "user".into(),
                content: Some("Follow the Latest User Request in the SESSION CONTEXT above. Use tools now to explore and solve the task.".into()),
                tool_calls: None,
                tool_call_id: None,
            });
        }

        msgs
    }

    /// Handle session meta + file summary cache tools. Returns Some(ack) if handled.
    async fn handle_session_tool(&mut self, name: &str, args_json: &str) -> Option<String> {
        let args: serde_json::Value = serde_json::from_str(args_json).unwrap_or_else(|_| json!({}));

        if name == "complete_plan_step" {
            if self.current_agent_mode() != "work" || !self.plan_tool_context().plan_executing {
                return Some(
                    "❌ complete_plan_step is only available in work mode while an approved plan is executing."
                        .to_string(),
                );
            }
            let mut session_take = self.session.take();
            let outcome = crate::plan_execution::complete_plan_step(
                &mut self.plan_exec,
                &self.config.tool_backend,
                &self.config.workspace,
                session_take.as_mut(),
                &args,
            )
            .await;
            self.session = session_take;
            return Some(match outcome {
                crate::plan_execution::CompletePlanStepOutcome::Accepted { message } => {
                    format!("✓ {message}")
                }
                crate::plan_execution::CompletePlanStepOutcome::Failed { message } => {
                    format!("✗ {message}")
                }
                crate::plan_execution::CompletePlanStepOutcome::NeedsUserObservation {
                    prompt,
                    step_index,
                } => format!(
                    "⏸ Step {} requires user observation before continuing. Prompt shown to user: {}",
                    step_index + 1,
                    prompt
                ),
                crate::plan_execution::CompletePlanStepOutcome::Rejected { message } => {
                    format!("❌ {message}")
                }
            });
        }

        if name == "revise_plan_step" {
            let plan_executing = self.plan_tool_context().plan_executing;
            if self.current_agent_mode() != "plan"
                && !(self.current_agent_mode() == "work" && plan_executing)
            {
                return Some(
                    "❌ revise_plan_step is only available during plan mode or work mode with an active plan."
                        .to_string(),
                );
            }
            if let Some(s) = self.session.as_mut() {
                let exec = if plan_executing {
                    Some(&mut self.plan_exec)
                } else {
                    None
                };
                match crate::plan_execution::revise_plan_step(s, &args, exec) {
                    Ok(msg) => return Some(msg),
                    Err(e) => return Some(format!("❌ {e}")),
                }
            }
            return Some("❌ No session available for revise_plan_step.".to_string());
        }

        if name == "update_goal" {
            if let Some(s) = &mut self.session {
                let goal = args
                    .get("goal")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let tests = args.get("tests").and_then(|v| v.as_array()).map(|a| {
                    a.iter()
                        .filter_map(|x| x.as_str().map(|s| s.to_string()))
                        .collect::<Vec<_>>()
                });
                let pits = args.get("pitfalls").and_then(|v| v.as_array()).map(|a| {
                    a.iter()
                        .filter_map(|x| x.as_str().map(|s| s.to_string()))
                        .collect::<Vec<_>>()
                });
                let _ = s.update_goal(&goal, tests, pits);
                return Some(format!(
                    "Goal, tests and pitfalls updated in session meta. New goal: {}",
                    goal
                ));
            }
        }

        if name == "define_done" {
            if let Some(s) = &mut self.session {
                if s.meta.completion_criteria.is_none() {
                    let definition = args
                        .get("definition")
                        .and_then(|v| v.as_str())
                        .unwrap_or("")
                        .to_string();
                    if !definition.trim().is_empty() {
                        s.meta.completion_criteria = Some(definition.clone());
                        s.save_meta().ok();
                        self.log_harness_event(
                            "define_done_called",
                            &format!(
                                "Agent successfully called define_done. Criteria set to: {}",
                                definition
                            ),
                        );
                        return Some(format!("Completion criteria defined (set once). Judge will use this to decide when done and clear it on fulfillment: {}", definition));
                    }
                } else {
                    return Some("Completion criteria already set (one-time only). Judge clears it on completion.".to_string());
                }
            }
        }

        if name == "record_discovery" {
            if let Some(s) = &mut self.session {
                let text = args
                    .get("text")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_string();
                let _ = s.record_discovery(&text);
                return Some(format!("Discovery recorded in session: {}", text));
            }
        }

        // Catch common hallucinated tool names early with a helpful message
        // (before falling through to normal tool execution).
        if matches!(name, "edit" | "str_replace" | "search_replace" | "modify_file") {
            return Some("❌ There is no 'edit' tool. The correct tool for search/replace edits is `patch` (parameters: path, search, replace, optional near_line; add wiki=true for the session wiki). Use `read` first to get exact text to search for.".to_string());
        }

        // Wiki flag: when wiki=true is set on read/write/patch/list, route to the
        // session's private wiki directory instead of the workspace.
        // Wiki writes are always allowed (no approval needed) — it's the agent's own scratchpad.
        let mut is_wiki = args.get("wiki").is_some_and(|v| {
            if let Some(b) = v.as_bool() {
                b
            } else if let Some(s) = v.as_str() {
                matches!(s.trim().to_lowercase().as_str(), "true" | "1" | "yes" | "on")
            } else if let Some(n) = v.as_i64() {
                n != 0
            } else {
                false
            }
        });
        // Auto-detect: if path starts with "wiki/" but wiki=true wasn't set,
        // the model forgot the flag. Route to wiki anyway (strip_wiki_prefix handles cleanup).
        if !is_wiki && matches!(name, "read" | "write" | "patch" | "list") {
            if let Some(p) = args.get("path").and_then(|v| v.as_str()) {
                let trimmed = p.trim().trim_start_matches("./");
                if trimmed.starts_with("wiki/") || trimmed.starts_with("wiki\\") || trimmed == "wiki" {
                    is_wiki = true;
                }
            }
        }
        if is_wiki && matches!(name, "read" | "write" | "patch" | "list") {
            if let Some(s) = &self.session {
                let path = args.get("path").and_then(|v| v.as_str()).unwrap_or("");
                match name {
                    "read" => {
                        let lines = args.get("lines").and_then(|v| v.as_str());
                        let full = args.get("full").is_some_and(|v| {
                            if let Some(b) = v.as_bool() { b } else if let Some(s) = v.as_str() {
                                matches!(s.trim().to_lowercase().as_str(), "true"|"1"|"yes")
                            } else if let Some(n) = v.as_i64() { n != 0 } else { false }
                        });
                        let limit = self.config.context_budget.read_line_limit;
                        return Some(s.read_wiki_file(path, lines, full, limit));
                    }
                    "write" => {
                        let content = args.get("content").and_then(|v| v.as_str()).unwrap_or("");
                        let _ = s.ensure_wiki_dir();
                        return Some(s.write_wiki_file(path, content));
                    }
                    "patch" => {
                        let search = args.get("search").and_then(|v| v.as_str()).unwrap_or("");
                        let replace = args.get("replace").and_then(|v| v.as_str()).unwrap_or("");
                        let near_line = args.get("near_line").and_then(|v| v.as_i64());
                        let _ = s.ensure_wiki_dir();
                        return Some(s.patch_wiki_file(path, search, replace, near_line));
                    }
                    "list" => {
                        let sub = if path.is_empty() { None } else { Some(path) };
                        let _ = s.ensure_wiki_dir();
                        return Some(s.list_wiki(sub));
                    }
                    _ => unreachable!(),
                }
            }
            return Some(format!("❌ {}(wiki=true): no active session", name));
        }

        if name == "read_summary" {
            let path = args.get("path").and_then(|v| v.as_str()).unwrap_or("");
            let rel = make_rel_path(path, &self.config.workspace);
            if let Some(s) = &self.session {
                if let Ok(Some((_, summary))) = s.get_file_summary(&rel) {
                    return Some(format!("📄 {} (fresh summary):\n{}", rel, summary));
                }
                // Cache miss or stale: deliver (capped) raw content + current mtime so the
                // caller can analyze and later call store_summary(path, mtime, summary).
                let raw = tools::read_file(
                    path,
                    None,
                    &self.config.workspace,
                    self.config.context_budget.read_line_limit,
                    false,
                );
                let mtime =
                    crate::session::current_file_mtime_for_agent(&self.config.workspace.join(&rel));
                return Some(format!(
                    "📄 {} (mtime={}, stale/missing - analyze below then call store_summary(path=\"{}\", mtime={}, summary=\"your concise summary\")):\n{}",
                    rel, mtime, path, mtime, raw
                ));
            }
            // Fallback (no session): just do a normal read
            let raw = tools::read_file(
                path,
                None,
                &self.config.workspace,
                self.config.context_budget.read_line_limit,
                false,
            );
            return Some(format!("📄 {}:\n{}", rel, raw));
        }

        if name == "store_summary" {
            if let Some(s) = &self.session {
                let p = args.get("path").and_then(|v| v.as_str()).unwrap_or("");
                let rel = make_rel_path(p, &self.config.workspace);
                let mtime = args.get("mtime").and_then(|v| v.as_i64()).unwrap_or(0);
                let summary = args.get("summary").and_then(|v| v.as_str()).unwrap_or("");
                let _ = s.store_file_summary(&rel, mtime, summary);
                return Some(format!("✅ summary stored for {} @ mtime={}", rel, mtime));
            }
            return Some("✅ store_summary (no session)".to_string());
        }

        None
    }

    fn maybe_invalidate_summary(&mut self, name: &str, args: &serde_json::Value) {
        if name == "write" || name == "patch" {
            if let Some(s) = &self.session {
                if let Some(p) = args.get("path").and_then(|v| v.as_str()) {
                    let rel = make_rel_path(p, &self.config.workspace);
                    let _ = s.invalidate_file_summary(&rel);
                }
            }
        }
    }

    async fn persist_turn(&mut self) {
        // Append all unlogged messages to full_log.jsonl (assistant + tool calls + results).
        if let Some(s) = &self.session {
            while self.logged_message_count < self.conversation.len() {
                let msg = &self.conversation[self.logged_message_count];
                let tool_names: Vec<&str> = msg
                    .tool_calls
                    .as_ref()
                    .map(|tcs| tcs.iter().map(|tc| tc.function.name.as_str()).collect())
                    .unwrap_or_default();

                // Include full tool call input details (name + arguments) when the
                // assistant message contains tool_calls. This makes tool *inputs*
                // available in full_log.jsonl for debugging/replay without logging
                // raw tool *outputs* (those are sanitized + truncated before being
                // put into the "tool" role messages that go to the model and the log).
                let tool_calls_detail = msg.tool_calls.as_ref().map(|tcs| {
                    tcs.iter().map(|tc| {
                        let args_val: serde_json::Value = serde_json::from_str(&tc.function.arguments)
                            .unwrap_or_else(|_| serde_json::json!(tc.function.arguments));
                        serde_json::json!({
                            "id": &tc.id,
                            "function": {
                                "name": &tc.function.name,
                                "arguments": args_val
                            }
                        })
                    }).collect::<Vec<_>>()
                });

                let entry = serde_json::json!({
                    "ts": chrono::Utc::now().to_rfc3339(),
                    "role": msg.role,
                    "content": msg.content,
                    "has_tool_calls": msg.tool_calls.is_some(),
                    "tool_call_id": msg.tool_call_id,
                    "tool_names": tool_names,
                    "tool_calls": tool_calls_detail,
                });
                let _ = s.append_log(&entry.to_string());
                self.logged_message_count += 1;
            }
            // Rolling recent-turns summary refresh. Don't do this too often: each
            // call consumes one LLM round (and for mock backends, depletes the
            // scripted response queue). The heavy prune_history at 48 messages
            // handles full compression.
            if self.conversation.len() >= 24
                && self.conversation.len().is_multiple_of(12)
                && !matches!(*self.client.lock().await, ChatBackend::Mock(_))
            {
                let last_few: Vec<_> = self.conversation.iter().rev().take(6).cloned().collect();
                if !last_few.is_empty() {
                    let sm = self.summarize_messages(&last_few).await;
                    let label = self.generate_session_label().await;
                    if let Some(s_mut) = &mut self.session {
                        let prev = &s_mut.meta.recent_turns_summary;
                        let merged = if prev.is_empty() {
                            sm
                        } else {
                            format!("{}\n{}", prev, sm)
                        };
                        let trimmed = if merged.len() > SUMMARY_CHAR_LIMIT {
                            tools::safe_truncate(&merged, SUMMARY_CHAR_LIMIT).to_string() + "..."
                        } else {
                            merged
                        };
                        let _ = s_mut.set_recent_turns_summary(&trimmed);

                        // Keep label fresh whenever we touch the summary
                        let _ = s_mut.set_session_label(&label);
                    }
                }
            }
        }
    }

    /// Force-update the (cheap) session label for the picker and, occasionally,
    /// the recent_turns_summary. Called at the end of each turn so that session
    /// state on disk is reasonably fresh if the process is killed/restarted.
    ///
    /// We deliberately do *not* summarize on every turn (or even every 5th).
    /// Summarization is expensive (an extra LLM call). The heavy lifting is in
    /// prune_history (at 48 msgs) and the lighter periodic refresh in persist_turn
    /// (every 12 msgs once >= 24). Here we only do a light refresh every 12 as well.
    pub async fn force_flush_session(&mut self) {
        if self.conversation.len() < 2 {
            return;
        }

        // Label is cheap (heuristic, no LLM call) — always refresh it so the
        // picker shows a good description even after restarts.
        let label = self.generate_session_label().await;

        let len = self.conversation.len();
        let is_mock = matches!(*self.client.lock().await, ChatBackend::Mock(_));

        let needs_full = {
            let s_ref = self.session.as_ref();
            s_ref.is_none_or(|s| s.meta.recent_turns_summary.is_empty())
                || (len >= 24 && len.is_multiple_of(12) && !is_mock)
        };

        let summary_for_meta = if needs_full {
            let recent: Vec<_> = self.conversation.iter().rev().take(6).cloned().collect();
            if recent.is_empty() {
                None
            } else {
                let sm = self.summarize_messages(&recent).await;
                let prev = self.session.as_ref()
                    .map(|s| s.meta.recent_turns_summary.clone())
                    .unwrap_or_default();
                let merged = if prev.is_empty() {
                    sm
                } else {
                    format!("{}\n{}", prev, sm)
                };
                Some(merged)
            }
        } else {
            None
        };

        if let Some(s) = &mut self.session {
            let _ = s.set_session_label(&label);

            if needs_full {
                if let Some(sm) = summary_for_meta {
                    let trimmed = if sm.len() > SUMMARY_CHAR_LIMIT {
                        tools::safe_truncate(&sm, SUMMARY_CHAR_LIMIT).to_string() + "..."
                    } else {
                        sm
                    };
                    let _ = s.set_recent_turns_summary(&trimmed);
                }
            }
        }
    }

    /// Current exec approval mode from the session (for UI to decide on dialogs)
    pub fn current_exec_mode(&self) -> crate::session::ExecApprovalMode {
        self.session
            .as_ref()
            .map(|s| s.meta.exec_approval_mode)
            .unwrap_or_default()
    }

    /// Update the exec approval mode (from /mode UI) and persist if possible.
    pub fn set_exec_approval_mode(&mut self, mode: crate::session::ExecApprovalMode) {
        if let Some(s) = &mut self.session {
            s.meta.exec_approval_mode = mode;
            // note: caller should save_meta if needed
        }
    }

    /// Current agent operating mode (talk/think/research/work/dream).
    pub fn current_agent_mode(&self) -> String {
        self.session
            .as_ref()
            .map(|s| {
                let m = s.meta.agent_mode.trim();
                if m.is_empty() {
                    "talk".to_string()
                } else {
                    m.to_string()
                }
            })
            .unwrap_or_else(|| "talk".to_string())
    }

    /// For Super Judge (work mode) to perform its own LLM calls.
    pub fn backend(&self) -> Arc<Mutex<ChatBackend>> {
        self.client.clone()
    }

    /// Set agent operating mode and persist.
    pub fn set_agent_mode(&mut self, mode: &str) {
        let normalized = normalize_agent_mode(mode);
        if let Some(s) = &mut self.session {
            s.meta.agent_mode = normalized;
        }
    }

    /// Estimate tokens for the full prompt we would send (system + session injection + conversation).
    pub fn estimated_context_tokens(&self) -> u32 {
        let messages = self.build_messages_for_model();
        let total_bytes: usize = messages.iter().map(message_byte_size).sum();
        (total_bytes as f64 / 3.5) as u32
    }

    /// Switch the inference backend without losing conversation history.
    /// Re-creates the LlmClient with the new endpoint config.
    pub async fn switch_endpoint(
        &mut self,
        endpoint: &crate::config::InferenceEndpoint,
        budget: crate::config::ContextBudget,
    ) {
        self.config.base_url = endpoint.base_url.clone();
        self.config.model = endpoint.model.clone();
        self.config.api_key = endpoint.api_key.clone();
        self.config.context_budget = budget;
        self.client.lock().await.reset_http(self.config.clone());
    }

    /// Read-only access to the current config (for UI to display active endpoint).
    pub fn current_config(&self) -> &Config {
        &self.config
    }

    pub fn enable_judge(&self) -> bool {
        self.config.enable_judge
    }

    /// Number of messages in the live conversation (for test assertions).
    #[allow(dead_code)]
    pub fn conversation_len(&self) -> usize {
        self.conversation.len()
    }

    /// Read-only access to the session (for test assertions on meta, log, etc.).
    #[allow(dead_code)]
    pub fn session_ref(&self) -> Option<&crate::session::Session> {
        self.session.as_ref()
    }

    #[allow(dead_code)]
    pub fn has_session(&self) -> bool {
        self.session.is_some()
    }

    /// Return the full messages array the model would receive on the next call.
    /// Used by `--dump-prompt` for debugging prompt construction without running inference.
    pub fn dump_prompt(&self) -> Vec<Message> {
        self.build_messages_for_model()
    }

    /// Uses a lightweight inference call to analyze the current state.
    /// It decides:
    /// - whether the request/goal has been fulfilled, or
    /// - whether the model is looping unproductively and should ask the user for help.
    ///
    /// This replaces pure hardcoded nudge/continue counts with smarter judgment.
    pub async fn judge_turn(
        &self,
        last_assistant_text: &str,
        recent_actions: &[ActionRecord],
    ) -> TurnJudge {
        if let Some(ref judge) = self.judge {
            if let Some(ref s) = self.session {
                judge
                    .judge_turn(&s.meta, last_assistant_text, recent_actions)
                    .await
            } else {
                TurnJudge::Continue { suggestion: None }
            }
        } else {
            TurnJudge::Continue { suggestion: None }
        }
    }
}

fn message_byte_size(m: &Message) -> usize {
    let content_len = m.content.as_ref().map_or(0, |c| c.len());
    let tc_len = m.tool_calls.as_ref().map_or(0, |tcs| {
        tcs.iter()
            .map(|tc| tc.id.len() + tc.function.name.len() + tc.function.arguments.len())
            .sum::<usize>()
    });
    let id_len = m.tool_call_id.as_ref().map_or(0, |s| s.len());
    content_len + tc_len + id_len + m.role.len() + 16
}

/// Rough token estimate. Matches the bytes_per_token heuristic used for budgets
/// (3.5 bytes/token is conservative for code-heavy content).
pub(crate) fn estimate_tokens(s: &str) -> u32 {
    (s.len() as f64 / 3.5) as u32
}

/// Strip <command_context> ... </command_context> (and similar nested planning blocks)
/// from summary text. Prevents the rolling recent_turns_summary from turning
/// the agent's internal exploration plans or sub-queries into persistent goals
/// that get re-injected every turn (a major source of rabbitholes).
fn strip_command_context_blocks(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut in_block = false;
    let mut depth = 0;
    for line in s.lines() {
        let l = line.trim_start();
        if l.starts_with("<command_context")
            || l.starts_with("<task_description")
            || l.starts_with("<user_query")
        {
            in_block = true;
            depth += 1;
            continue;
        }
        if in_block {
            if l.starts_with("</command_context")
                || l.starts_with("</task_description")
                || l.starts_with("</user_query")
                || l.contains("</command_context>")
            {
                depth -= 1;
                if depth <= 0 {
                    in_block = false;
                    depth = 0;
                }
                continue;
            }
            if l.starts_with('<') && !l.starts_with("</") {
                depth += 1;
            }
            continue;
        }
        out.push_str(line);
        out.push('\n');
    }
    out.trim().to_string()
}

fn truncate_for_context(s: &str, limit: usize) -> String {
    if s.len() <= limit {
        s.to_string()
    } else {
        format!(
            "{}...\n... ({} bytes total, truncated for context)",
            tools::safe_truncate(s, limit),
            s.len()
        )
    }
}

#[cfg(test)]
mod integration_tests {
    use super::*;
    use crate::chat_backend::{mock_tool_call, ChatBackend};
    use crate::config::{ContextBudget, ContextSource};
    use crate::llm::ChatResponse;
    use crate::tools::backend::{MockToolBackend, ToolBackend};
    fn mock_eval_config() -> Config {
        let workspace =
            std::env::temp_dir().join(format!("raven_agent_integ_{}", std::process::id()));
        let _ = std::fs::create_dir_all(&workspace);
        Config {
            base_url: "http://mock.local/v1".into(),
            model: "mock-model".into(),
            api_key: None,
            workspace,
            temperature: 0.0,
            max_tokens: 512,
            max_rounds: 5,
            prebuilt_session: None,
            context_budget: ContextBudget {
                context_tokens: 8192,
                tool_result_bytes: 4000,
                read_line_limit: 80,
                source: ContextSource::Default,
            },
            tool_backend: ToolBackend::Mock(MockToolBackend::from_json(&serde_json::json!({
                "list": { ".": "README.md\n" }
            }))),
            tools_enabled: true,
            enable_judge: false,
            flags: crate::runtime::RuntimeFlags::default(),
            harness: crate::runtime::EvalHarness::default(),
        }
    }

    #[tokio::test]
    async fn mock_llm_and_tools_complete_run_turn() {
        let chat = ChatBackend::Mock(crate::chat_backend::MockChatBackend::new(vec![
            ChatResponse {
                content: String::new(),
                tool_calls: vec![mock_tool_call("list", r#"{"path":"."}"#)],
                finish_reason: None,
                usage: None,
                reasoning_content: None,
            },
            ChatResponse {
                content: "Workspace contains README.md mock fixture.".into(),
                tool_calls: vec![],
                finish_reason: Some("stop".into()),
                usage: None,
                reasoning_content: None,
            },
        ]));

        let mut agent = Agent::new(mock_eval_config(), chat);
        let result = agent
            .run_turn("List files and summarize.")
            .await
            .expect("run_turn");

        assert!(result.final_text.contains("README"));
        assert_eq!(result.actions.len(), 1);
        assert_eq!(result.actions[0].tool, "list");
    }

    #[tokio::test]
    async fn plan_mode_denies_non_wiki_writes_but_allows_wiki_and_update_goal() {
        let plan_write_args = serde_json::json!({
            "path": "plan.md",
            "content": "# Plan for ASCII cake script",
            "wiki": true
        }).to_string();
        let impl_write_args = serde_json::json!({
            "path": "birthday_cake.py",
            "content": "print('cake')"
        }).to_string();
        let update_args = serde_json::json!({
            "goal": "Write ascii cake script",
            "tests": ["script runs and prints cake"]
        }).to_string();

        let chat = ChatBackend::Mock(crate::chat_backend::MockChatBackend::new(vec![
            // First turn in plan mode: agent does update_goal + write to wiki (plan.md)
            ChatResponse {
                content: String::new(),
                tool_calls: vec![
                    mock_tool_call("update_goal", &update_args),
                    mock_tool_call("write", &plan_write_args),
                ],
                finish_reason: None,
                usage: None,
                reasoning_content: None,
            },
            // Second turn: tries a workspace write (should be denied by guard)
            ChatResponse {
                content: String::new(),
                tool_calls: vec![mock_tool_call("write", &impl_write_args)],
                finish_reason: None,
                usage: None,
                reasoning_content: None,
            },
            // Third: after proceed (mode will be switched outside in real flow), does real write
            ChatResponse {
                content: String::new(),
                tool_calls: vec![mock_tool_call("write", &impl_write_args)],
                finish_reason: Some("stop".into()),
                usage: None,
                reasoning_content: None,
            },
        ]));

        let mut cfg = mock_eval_config();
        // Give it a session so wiki + meta work
        let ws = cfg.workspace.clone();
        let session = crate::session::Session::init(&ws).unwrap();
        cfg.prebuilt_session = Some(session);

        let mut agent = Agent::new(cfg, chat);
        agent.set_agent_mode("plan");

        // Turn 1: clarification / planning turn (update_goal + wiki write)
        let r1 = agent.run_turn("write a python script for an ascii birthday cake").await.expect("r1");
        // Should have performed the wiki write (no denial)
        let actions1: Vec<_> = r1.actions.iter().map(|a| a.tool.as_str()).collect();
        assert!(actions1.contains(&"write") || actions1.contains(&"update_goal"), "planning actions: {:?}", actions1);

        // Turn 2: while still in plan, a workspace write should be denied by the guard (produces denial record)
        // We don't assert exact string here because action recording for denials may surface in conversation;
        // the important thing is we don't get a normal successful write side-effect for non-wiki.
        let _r2 = agent.run_turn("ok I will just write the cake script now").await.expect("r2");

        // The harness (input_handler) would detect "proceed" and switch the mode
        agent.set_agent_mode("work");
        assert_eq!(agent.current_agent_mode(), "work");

        // At this point further writes would be allowed by the guard (the previous
        // plan-mode write attempt for non-wiki would have been denied inside execute_and_record).
        // We simply assert that we can continue running turns after the mode change.
        let r3 = agent.run_turn("now implement the script").await.expect("r3 after switch");
        // r3 may or may not contain a write depending on mock responses left; the key
        // is that the agent is no longer restricted by the plan-mode guard.
        let _ = r3;
    }
}
